language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test

machine:
  environment:
    CC_TEST_REPORTER_ID: db85f74898e5718c116a69ad917dcd6307e9f9561f2f28880226917cf0deb681

after_success:
  - codeclimate-test-reporter < ./test/unit/coverage/lcov.info
