language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=db85f74898e5718c116a69ad917dcd6307e9f9561f2f28880226917cf0deb681 ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./test/unit/coverage/lcov.info
